[package]
name = "sift-rs"
version = "0.1.0"
edition = "2021"
authors = ["Alexandr Meshkov <stevel705@outlook.com>"]
description = "SIFT implementation in Rust"
license = "MIT"
repository = "https://github.com/stevel705/sift-rs"
readme = "README.md"
keywords = ["sift", "feature-detection", "image-processing", "computer-vision"]
categories = ["image-processing", "computer-vision"]
documentation = "https://docs.rs/sift-rs"
homepage = "https://github.com/stevel705/sift-rs"
bugs = "https://github.com/stevel705/sift-rs/issues"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "sift"
path = "src/lib.rs"

[[bin]]
name = "sift"
path = "src/main.rs"

[dependencies]
image = "0.24.8"
ndarray = "0.15.6"
imageproc = "0.23.0"